# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Hung Tran"                                # Your name
  description: "This is a note where I write down my learning journey"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/my_image.jpg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/my_image.jpg
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:thaihung.tran306@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Tran Thai Hung </span>
      <span class="faux-block">All content licensed under<br>[Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: |
     
    right: |
      <span class="faux-block"><a href="https://github.com/TranHung93/my_note">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true